plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
highlighter: rouge
theme: jekyll-theme-cayman
title: "Rahul's Blog for Beginners"
description: "My blog for programming related information covering python, javascript, html, css and related technologies."
