plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman
title: "Rahul's Blog\nfor\nBeginners"
description:My blog for programming related information covering python, javascript, html, css and related technologies.
